apiVersion: batch/v1
kind: CronJob
metadata:
  name: import-products-cron
  namespace: import-products
spec:
  schedule: "*/5 * * * *"  # Executar a cada 5 minutos (modifique conforme necessário)
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: import-products
            image: vitorcostasilva/import-products:2.0
            command: ["/bin/bash", "-c", "/app/backend/cron.sh"]  # Caminho correto para o cron.sh
            resources:
              requests:
                cpu: "500m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "2Gi"
          restartPolicy: Never  # Não reiniciar o Pod após a execução
      backoffLimit: 4  # Tentar novamente até 4 vezes em caso de falha
