apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: import-products
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: exec-role
  namespace: import-products
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create", "exec"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-rolebinding
  namespace: import-products
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: exec-role
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: import-products
