apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "import-products.fullname" . }}-cron
  namespace: {{ include "import-products.fullname" . }}
spec:
  schedule: "*/5 * * * *"  # Executar a cada 5 minutos, ajuste conforme necessário
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cronjob-sa
          containers:
          - name: kubectl-exec
            image: bitnami/kubectl:latest  # Use uma imagem com kubectl instalado
            command:
              - /bin/sh
              - -c
              - |
                PODS=$(kubectl get pods -l app=import-products -o jsonpath='{.items[*].metadata.name}' -n import-products)
                for POD in $PODS; do
                  echo "Running cron.py in $POD"
                  kubectl exec -n import-products $POD -- /bin/sh -c '
                    cd /app/backend
                    export UPLOAD_DIR=uploads
                    python3 -m src.cron
                    if [ "$?" = "0" ]; then
                      echo "Path $UPLOAD_DIR is cleaned !!"
                    fi
                  '
                done
          restartPolicy: Never
      backoffLimit: 3
