apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "import-products.fullname" . }}-route
  namespace: {{ .Release.Namespace }} # Should match your service namespace
spec:
  parentRefs:
  - name: apps
    namespace: envoy-gateway-system
    sectionName: https # Targets the port 443 listener
  hostnames:
  - "import-products.demo.com"
  rules:
  # 1. API Rule with Path Rewrite
  - matches:
    - path:
        type: PathPrefix
        value: /api
    filters:
    - type: URLRewrite
      urlRewrite:
        path:
          type: ReplacePrefixMatch
          replacePrefixMatch: / # This replaces the Nginx rewrite-target logic
    backendRefs:
    - name: import-products #{{ include "import-products.fullname" . }}
      port: 81

  # 2. Frontend Rule (Root)
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: import-products #{{ include "import-products.fullname" . }}
      port: 80