apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: import-products
type: Opaque
data:
  DATABASE_HOST: {{ .Values.mongodb.host }}
  DATABASE_USER: {{ .Values.mongodb.username }}
  DATABASE_PASS: {{ .Values.mongodb.password }}
  DATABASE_DBNAME: {{ .Values.mongodb.host }}