apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-{{ include "import-products.fullname" . }}
  name: db-{{ include "import-products.fullname" . }}
  #namespace: {{ include "import-products.fullname" . }}
spec:
  selector:
    app: db-{{ include "import-products.fullname" . }}
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for stable DNS
  # type: ClusterIP
