apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ include "import-products.fullname" . }}
    {{- include "import-products.labels" . | nindent 4 }}
  name: {{ include "import-products.fullname" . }}
  #namespace: {{ include "import-products.fullname" . }}
spec:
  ports:
  - name: backend-port
    port: 81
    protocol: TCP
    targetPort: {{ .Values.backend_port | default 8081 }}  # Backend application (FastAPI)
  - name: frontend-port
    port: 80
    protocol: TCP
    targetPort: {{ .Values.frontend_port | default 8080 }}  # Frontend application
  selector:
    app: {{ include "import-products.fullname" . }}
  type: ClusterIP
