version: "3.8"

services:
  db-prova:
    image: postgres:10
    restart: always
    container_name: db-prova
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db_prova
      - TZ=America/Sao_Paulo
    volumes:
      - $PWD/database/scripts:/docker-entrypoint-initdb.d

  app-prova:
    build:
      context: .
    restart: always
    container_name: app-prova
    environment:
      - DATABASE_HOST=db-prova
      - DATABASE_USER=root
      - DATABASE_PASS=secret
      - DATABASE_DBNAME=db_prova
      - UPLOAD_DIR=/app/backend/uploads
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db-prova
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./logs/logs_backend.txt:/app/backend/output.log