apiVersion: v1
kind: Secret
metadata:
  name: credentials
  namespace: import-products
type: Opaque
data:
  DATABASE_HOST: ZGItaW1wb3J0LXByb2R1Y3Rz
  DATABASE_USER: cm9vdA==
  DATABASE_PASS: c2VjcmV0
  DATABASE_DBNAME: ZGItaW1wb3J0LXByb2R1Y3Rz
  # UPLOAD_DIR: 