apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: import-products-ingress
  namespace: import-products
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/use-regex: "true"
    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   proxy_set_header Host $host;
spec:
  ingressClassName: nginx
  rules:
  - host: import-products.demo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: import-products
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: import-products
            port:
              number: 81
