apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db-import-products
  name: db-import-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-import-products
  template:
    metadata:
      labels:
        app: db-import-products
    spec:
      containers:
      - name: db-import-products
        image: postgres:10
        env:
          - name: POSTGRES_USER
            value: root
          - name: POSTGRES_PASSWORD
            value: secret
          - name: POSTGRES_DB
            value: db_prova
          - name: TZ
            value: "America/Sao_Paulo"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
          - name: db-scripts
            mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: db-data
          emptyDir: {}
        - name: db-scripts
          hostPath:
            path: /Users/vitordacostasilva/Documents/Vitor/Projetos/engenheiro-devops-pleno-01235-2023-047.652.431-84/database/scripts
