apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: import-products
  name: import-products
spec:
  replicas: 3
  selector:
    matchLabels:
      app: import-products
  template:
    metadata:
      labels:
        app: import-products
    spec:
      containers:
      - image: vitorcostasilva/import-products:1.0
        name: import-products
        resources:
          requests:
            cpu: 0.5  #Recursos de CPU
            memory: 512Mi  #Recursos de memória
          limits:
            cpu: 1  #Recursos de CPU
            memory: 1Gi 
        env:
          - name: DATABASE_HOST
            value: db-prova
          - name: DATABASE_USER
            value: root
          - name: DATABASE_PASS
            value: secret
          - name: DATABASE_DBNAME
            value: db_prova
          - name: UPLOAD_DIR
            value: /app/backend/uploads
        ports:
          - containerPort: 8080
          - containerPort: 8081
