apiVersion: v1
entries:
  import-products:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-03T22:51:35.119114545Z"
    description: A Helm chart for install import-products in the cluster Kubernetes
    digest: 41d3792dc9bf93375b9433ca12e6971cf67f6e87da542ab7cf4117424bb40f7b
    name: import-products
    type: application
    urls:
    - https://raw.githubusercontent.com/vitor-csilva/importacao-produtos-web/develop/k8s/helm/import-products/charts/import-products-2.0.0.tgz
    version: 2.0.0
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2025-04-03T22:51:35.116824593Z"
    description: A Helm chart for install import-products in the cluster Kubernetes
    digest: 3cbb53aeb2eb063727f81886272822f21d909bfd4a635a652df02bfcdf02675b
    name: import-products
    type: application
    urls:
    - https://raw.githubusercontent.com/vitor-csilva/importacao-produtos-web/develop/k8s/helm/import-products/charts/import-products-1.0.0.tgz
    version: 1.0.0
generated: "2025-04-03T22:51:35.115446859Z"
