apiVersion: v1
kind: Service
metadata:
  labels:
    app: import-products
  name: import-products
  namespace: import-products
spec:
  ports:
  - name: backend-port
    port: 81
    protocol: TCP
    targetPort: 8081  # Backend application (FastAPI)
  - name: frontend-port
    port: 80
    protocol: TCP
    targetPort: 8080  # Frontend application
  selector:
    app: import-products
  type: ClusterIP
