apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-prova
  name: app-prova
  namespace: default
spec:
  ports:
  - name: port-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: port-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: app-prova
  type: ClusterIP
