apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-prova
  name: db-prova
spec:
  selector:
    app: db-prova
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
