apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-import-products
  name: db-import-products
  namespace: import-products
spec:
  selector:
    app: db-import-products
  ports:
    - name: db-port
      protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None  # Headless service for stable DNS
  # type: ClusterIP
