# This is a basic workflow to help you get started with Actions
name: Build and Push Docker Image & Update Helm Chart import-products

on:
  push:
    branches: [ "main","develop" ]
    # paths:
    #   - 'Dockerfile'
    #   - 'backend/**'
    #   - 'frontend/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CHARTS_DIR: ./k8s/helm/import-products/charts
  HELM_DIR: ./k8s/helm/import-products
  REPO_URL: https://raw.githubusercontent.com/vitor-csilva/importacao-produtos-web/develop/k8s/helm/import-products/charts

jobs:
  build-and-push-image:
    if: ${{ true }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          #platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
  
  package-and-push-helm:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        # with:
        #   version: v3.14.0
        id: install

      - name: Package Helm Chart
        run: |
          ls ${{ env.HELM_DIR }} -lha
          mkdir -p ${{ env.CHARTS_DIR }}
          rm -f ${{ env.CHARTS_DIR }}/index.yaml
          helm package ${{ env.HELM_DIR }} -d ${{ env.CHARTS_DIR }}

      - name: Update Helm Index
        run: |
          helm repo index ${{ env.CHARTS_DIR }} --url ${{ env.REPO_URL }}
      
      - name: Debug GH_PAT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ -z "${GH_TOKEN}" ]]; then
            echo "GH_PAT is not set!"
            exit 1
          else
            echo "${GH_TOKEN} is set successfully!"
          fi

      - name: Commit and Push Helm Chart
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GITHUB_TOKEN instead
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://${GH_TOKEN}@github.com/${{ github.repository }}.git
          git add ${{ env.CHARTS_DIR }}
          git commit -m "Update Helm chart package and index.yaml" || echo "No changes to commit"
          git push origin ${{ github.ref_name }} || echo "No changes to push"
        
        
