# This is a basic workflow to help you get started with Actions
name: Build and Push Docker Image and Update/Deploy Helm Chart import-products

on:
  push:
    branches: [ "main","develop" ]
    # paths:
    #   - 'Dockerfile'
    #   - 'backend/**'
    #   - 'frontend/**'

env:
  VERSION: 5.0.0
  REGISTRY: ghcr.io
  HELM_REGISTRY: registry-1.docker.io
  HELM_REPO: vitorcostasilva
  HELM_REPO_NAME: helm-import-products
  IMAGE_NAME: ${{ github.repository }}
  CHARTS_DIR: ./k8s/helm/import-products/helm-repo
  HELM_DIR: ./k8s/helm/import-products
  REPO_URL: https://raw.githubusercontent.com/vitor-csilva/importacao-produtos-web/develop/k8s/helm/import-products/helm-repo

jobs:
  build-and-push-image:
    if: ${{ true }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          #platforms: linux/amd64, linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}:latest
  
  package-and-push-helm:
    runs-on: ubuntu-latest
    needs: build-and-push-image

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # - name: Generate helm package dockerfile
      #   run: |
      #     docker build --build-arg TAG=${{ env.VERSION }} --build-arg REPO_PASSWORD=${{ env.REPO_PASSWORD }} -t ${{ env.HELM_REPO }}/${{ env.HELM_REPO_NAME }}:${{ env.VERSION }} -f ${{ env.HELM_DIR }}/Dockerfile .

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.0
        # with:
        #   version: v3.14.0
        id: install

      - name: Helm Login
        # env:
          # REPO_URL: registry-1.docker.io
          # REPO_USERNAME: vitorcostasilva
          # REPO_PASSWORD: ${{ env.REPO_PASSWORD }}
        run: |
          echo ${{ env.REPO_PASSWORD }} | helm registry login ${{ env.HELM_REGISTRY }}  -u ${{ env.HELM_REPO }} --password-stdin

      - name: Helm dependency update
        run: |
          cd ${{ env.HELM_DIR }}
          helm dependency update 

      - name: Helm Package
        # env:
        #   GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i "s/0.1.0/${{ env.VERSION }}/g" Chart.yaml
          sed -i "s/name: import-products/name: ${{ env.HELM_REPO_NAME }}/" Chart.yaml
          cat Chart.yaml
          helm package . --destination generated/
          ls -lha generated/
          helm push generated/${{ env.HELM_REPO_NAME }}-${{ env.VERSION }}.tgz oci://${{ env.HELM_REGISTRY }}/${{ env.HELM_REPO }}